import type { SceneDescription } from "../types"
import { SERIF, SANS, MONO } from "./fonts"

const svgUri = (svg: string) =>
	`data:image/svg+xml;utf8,${encodeURIComponent(svg)}`

const LEAD_L = `A Sunday front page lives on its contrasts: the heavy certainty of the masthead, the compressed urgency of the deck, the long patience of the columns beneath it. When editorial design works, every inset item has a purpose. The illustration advances the argument. The side note gives the reader a second register of information. The quote does not decorate the copy; it reframes it.`

const LEAD_R = `That is the threshold these presets need to cross. An editorial layout cannot feel like a stack of text boxes with a loose ornament drifting through the middle. It needs the clues of a real publication: issue markers, section labels, an image plate that looks commissioned, and the kind of annotated marginalia a reader expects from a thoughtful print package translated to the web.`

const SEC2_1 = `The technical novelty of a moving page only matters if the composition still feels edited while it moves. That means each object must carry actual semantic weight. A note card should read like reporting. A seal should suggest edition and authorship. The illustration should interrupt the columns with enough authority that its movement changes the reading path rather than merely bouncing around inside it.`

const SEC2_2 = `DOMino's advantage is that those interruptions are not simulated by swapping screenshots. The text is recomputed as geometry. Every line checks the space left by nearby obstacles, fills viable segments, and proceeds. The layout responds with the speed of a physics demo but with the density of a newspaper spread. That combination is what makes the page feel believable once it starts drifting.`

const SEC2_3 = `Richer presets matter because they teach a better instinct. They encourage building pages with side matter, evidence, and narrative staging rather than defaulting to boilerplate hero-copy-plus-card grids. The result is more than a nicer demo. It is a better model for what dynamic editorial interfaces could actually become.`

const DISPATCH = `Editors often describe a finished page as one that can survive being glanced at from several distances. At ten feet, the silhouette should be unmistakable. At one foot, the hierarchy should be legible. At reading distance, the small notes should reward attention. That is the standard a preset like this should aim for as well. Even when its plate, seal, and annotations are thrown out of place, the page should still read as a deliberate publication, not as a wrecked template.`

const EDITORIAL_PLATE = svgUri(`
<svg xmlns="http://www.w3.org/2000/svg" width="300" height="340" viewBox="0 0 300 340" fill="none">
  <rect width="300" height="340" rx="16" fill="#F7F1E7"/>
  <rect x="20" y="20" width="260" height="300" rx="12" fill="#FFFDFC" stroke="#D8CFC0"/>
  <rect x="40" y="42" width="220" height="116" rx="10" fill="#1F2937"/>
  <circle cx="108" cy="98" r="38" fill="#D4A373"/>
  <path d="M144 124C168 86 196 78 230 88V158H120C120 146 130 136 144 124Z" fill="#7C3AED"/>
  <rect x="40" y="176" width="120" height="12" rx="6" fill="#2C241F"/>
  <rect x="40" y="198" width="148" height="8" rx="4" fill="#C8BCAC"/>
  <rect x="40" y="214" width="206" height="8" rx="4" fill="#D6CCBF"/>
  <rect x="40" y="230" width="192" height="8" rx="4" fill="#E3DBD0"/>
  <rect x="40" y="258" width="92" height="28" rx="14" fill="#EEE7DA"/>
  <text x="58" y="276" fill="#8A5A21" font-size="12" font-family="Arial, sans-serif" font-weight="700">Plate I</text>
  <text x="160" y="277" fill="#6B645E" font-size="12" font-family="Arial, sans-serif">A page in motion</text>
</svg>
`)

export function createEditorialScene(vw: number, vh: number): SceneDescription {
	const w = Math.min(vw - 40, 940)
	const mx = Math.max(20, (vw - w) / 2)
	const H = Math.max(vh, 1660)
	const col2W = (w - 28) / 2
	const col3W = (w - 48) / 3

	return {
		id: "editorial",
		name: "Editorial",
		width: vw,
		height: H,
		backgroundColor: "#F4F0E8",
		elements: [
			{
				id: "e-r1",
				type: "divider",
				rect: { x: mx, y: 20, width: w, height: 3 },
				throwable: false,
				pinned: true,
				backgroundColor: "#1A1612",
			},
			{
				id: "e-mast",
				type: "heading",
				rect: { x: mx, y: 28, width: w, height: 50 },
				throwable: false,
				pinned: true,
				text: "The Editorial Engine",
				fontSize: 42,
				fontWeight: 700,
				fontFamily: SERIF,
				lineHeight: 48,
				color: "#1A1612",
			},
			{
				id: "e-vol",
				type: "heading",
				rect: { x: mx, y: 80, width: w / 2, height: 16 },
				throwable: false,
				pinned: true,
				text: "Vol. II  |  Sunday edition  |  March 2026",
				fontSize: 10,
				fontWeight: 500,
				fontFamily: MONO,
				lineHeight: 14,
				color: "#8F8578",
			},
			{
				id: "e-weather",
				type: "heading",
				rect: { x: mx + w - 220, y: 80, width: 120, height: 16 },
				throwable: false,
				pinned: true,
				text: "LONDON  9C  Clear",
				fontSize: 10,
				fontWeight: 500,
				fontFamily: MONO,
				lineHeight: 14,
				color: "#8F8578",
			},
			{
				id: "e-price",
				type: "badge",
				rect: { x: mx + w - 72, y: 74, width: 72, height: 22 },
				throwable: true,
				pinned: false,
				text: "$3.00",
				fontSize: 10,
				fontWeight: 700,
				fontFamily: MONO,
				color: "#1A1612",
				backgroundColor: "#FBF7F1",
				borderRadius: 0,
				border: "1px solid #C9BFAF",
				mass: 0.08,
			},
			{
				id: "e-r2",
				type: "divider",
				rect: { x: mx, y: 102, width: w, height: 1 },
				throwable: false,
				pinned: true,
				backgroundColor: "#B9AFA1",
			},
			{
				id: "e-r2b",
				type: "divider",
				rect: { x: mx, y: 105, width: w, height: 1 },
				throwable: false,
				pinned: true,
				backgroundColor: "#B9AFA1",
			},

			{
				id: "e-sec-1",
				type: "badge",
				rect: { x: mx, y: 112, width: 64, height: 20 },
				throwable: true,
				pinned: false,
				text: "ESSAY",
				fontSize: 9,
				fontWeight: 700,
				fontFamily: MONO,
				color: "#B45309",
				backgroundColor: "transparent",
				borderRadius: 0,
				mass: 0.04,
			},
			{
				id: "e-sec-2",
				type: "badge",
				rect: { x: mx + 72, y: 112, width: 76, height: 20 },
				throwable: true,
				pinned: false,
				text: "LAYOUT",
				fontSize: 9,
				fontWeight: 700,
				fontFamily: MONO,
				color: "#7C3AED",
				backgroundColor: "transparent",
				borderRadius: 0,
				mass: 0.04,
			},
			{
				id: "e-sec-3",
				type: "badge",
				rect: { x: mx + 156, y: 112, width: 78, height: 20 },
				throwable: true,
				pinned: false,
				text: "SUNDAY",
				fontSize: 9,
				fontWeight: 700,
				fontFamily: MONO,
				color: "#0F766E",
				backgroundColor: "transparent",
				borderRadius: 0,
				mass: 0.04,
			},

			{
				id: "e-hl",
				type: "heading",
				rect: { x: mx, y: 142, width: w, height: 42 },
				throwable: false,
				pinned: true,
				text: "The Page That Learns To Breathe",
				fontSize: 32,
				fontWeight: 700,
				fontFamily: SERIF,
				lineHeight: 38,
				color: "#1A1612",
			},
			{
				id: "e-deck",
				type: "paragraph",
				rect: { x: mx, y: 194, width: w, height: 56 },
				throwable: false,
				pinned: true,
				text: "A more believable editorial preset needs more than ornamental shapes. It needs the structure of a real spread: a commissioned-looking plate, notes that read like reporting, and a hierarchy that still makes sense after the reader starts disturbing it.",
				fontSize: 16,
				fontWeight: 400,
				fontFamily: SERIF,
				lineHeight: 24,
				color: "#5E574F",
			},
			{
				id: "e-by",
				type: "heading",
				rect: { x: mx, y: 258, width: w, height: 16 },
				throwable: false,
				pinned: true,
				text: "By the DOMino editorial board  |  Illustration generated in-scene  |  Layout reacts in real time",
				fontSize: 11,
				fontWeight: 500,
				fontFamily: MONO,
				lineHeight: 16,
				color: "#8F8578",
			},
			{
				id: "e-r3",
				type: "divider",
				rect: { x: mx, y: 286, width: w, height: 1 },
				throwable: false,
				pinned: true,
				backgroundColor: "#D8CEC0",
			},

			{
				id: "e-c1",
				type: "paragraph",
				rect: { x: mx, y: 304, width: col2W, height: 368 },
				throwable: false,
				pinned: true,
				text: LEAD_L,
				fontSize: 15,
				fontWeight: 400,
				fontFamily: SERIF,
				lineHeight: 24,
				color: "#2D2925",
			},
			{
				id: "e-c2",
				type: "paragraph",
				rect: { x: mx + col2W + 28, y: 304, width: col2W, height: 368 },
				throwable: false,
				pinned: true,
				text: LEAD_R,
				fontSize: 15,
				fontWeight: 400,
				fontFamily: SERIF,
				lineHeight: 24,
				color: "#2D2925",
			},
			{
				id: "e-plate",
				type: "image",
				rect: { x: mx + col2W - 20, y: 380, width: 212, height: 238 },
				throwable: true,
				pinned: false,
				backgroundColor: "#ECE5D8",
				borderRadius: 10,
				imageAlt: "Editorial illustration plate",
				imageSrc: EDITORIAL_PLATE,
				boxShadow: "0 14px 32px rgba(26,22,18,0.08)",
				mass: 1.95,
			},
			{
				id: "e-note",
				type: "card",
				rect: { x: mx + w - 178, y: 552, width: 178, height: 116 },
				throwable: true,
				pinned: false,
				text: "Editor's note",
				fontSize: 13,
				fontWeight: 700,
				fontFamily: SANS,
				color: "#1A1612",
				backgroundColor: "#FFFDF8",
				borderRadius: 12,
				padding: 16,
				border: "1px solid #D9D0C2",
				boxShadow: "0 8px 20px rgba(26,22,18,0.05)",
				mass: 0.9,
				children: [
					{
						id: "e-note-a",
						type: "paragraph",
						rect: { x: 0, y: 10, width: 0, height: 0 },
						throwable: false,
						pinned: true,
						text: "The plate is movable on purpose. It should alter the reading path, not sit politely in place.",
						fontSize: 12,
						fontWeight: 400,
						fontFamily: SANS,
						lineHeight: 17,
						color: "#6A625A",
					},
				],
			},

			{
				id: "e-r4",
				type: "divider",
				rect: { x: mx, y: 706, width: w, height: 1 },
				throwable: false,
				pinned: true,
				backgroundColor: "#CDBFAF",
			},
			{
				id: "e-mid-h",
				type: "heading",
				rect: { x: mx, y: 722, width: w, height: 24 },
				throwable: false,
				pinned: true,
				text: "What richer presets teach",
				fontSize: 22,
				fontWeight: 700,
				fontFamily: SERIF,
				lineHeight: 24,
				color: "#1A1612",
			},
			{
				id: "e-r5",
				type: "divider",
				rect: { x: mx, y: 754, width: w, height: 1 },
				throwable: false,
				pinned: true,
				backgroundColor: "#D8CEC0",
			},

			{
				id: "e-t1",
				type: "paragraph",
				rect: { x: mx, y: 772, width: col3W, height: 332 },
				throwable: false,
				pinned: true,
				text: SEC2_1,
				fontSize: 14,
				fontWeight: 400,
				fontFamily: SERIF,
				lineHeight: 22,
				color: "#3A352F",
			},
			{
				id: "e-t2",
				type: "paragraph",
				rect: { x: mx + col3W + 24, y: 772, width: col3W, height: 332 },
				throwable: false,
				pinned: true,
				text: SEC2_2,
				fontSize: 14,
				fontWeight: 400,
				fontFamily: SERIF,
				lineHeight: 22,
				color: "#3A352F",
			},
			{
				id: "e-t3",
				type: "paragraph",
				rect: { x: mx + (col3W + 24) * 2, y: 772, width: col3W, height: 332 },
				throwable: false,
				pinned: true,
				text: SEC2_3,
				fontSize: 14,
				fontWeight: 400,
				fontFamily: SERIF,
				lineHeight: 22,
				color: "#3A352F",
			},
			{
				id: "e-seal",
				type: "badge",
				rect: { x: mx + 32, y: 914, width: 58, height: 58 },
				throwable: true,
				pinned: false,
				text: "No.7",
				fontSize: 12,
				fontWeight: 700,
				fontFamily: MONO,
				color: "#fff",
				backgroundColor: "#B45309",
				borderRadius: 29,
				mass: 0.72,
			},
			{
				id: "e-pq",
				type: "card",
				rect: { x: mx + col3W + 22, y: 914, width: 224, height: 116 },
				throwable: true,
				pinned: false,
				text: '"A moving page still has to feel edited."',
				fontSize: 17,
				fontWeight: 500,
				fontFamily: SERIF,
				color: "#7C3AED",
				backgroundColor: "#FFFDF8",
				borderRadius: 12,
				padding: 16,
				border: "1px solid #D9D0C2",
				boxShadow: "0 8px 24px rgba(26,22,18,0.05)",
				mass: 0.95,
				children: [
					{
						id: "e-pq-a",
						type: "paragraph",
						rect: { x: 0, y: 10, width: 0, height: 0 },
						throwable: false,
						pinned: true,
						text: "That is what separates a demo asset from a real editorial surface.",
						fontSize: 12,
						fontWeight: 400,
						fontFamily: SANS,
						lineHeight: 17,
						color: "#6A625A",
					},
				],
			},

			{
				id: "e-r6",
				type: "divider",
				rect: { x: mx, y: 1154, width: w, height: 1 },
				throwable: false,
				pinned: true,
				backgroundColor: "#CDBFAF",
			},
			{
				id: "e-disp-h",
				type: "heading",
				rect: { x: mx, y: 1170, width: w, height: 24 },
				throwable: false,
				pinned: true,
				text: "Dispatches",
				fontSize: 22,
				fontWeight: 700,
				fontFamily: SERIF,
				lineHeight: 24,
				color: "#1A1612",
			},
			{
				id: "e-r7",
				type: "divider",
				rect: { x: mx, y: 1202, width: w, height: 1 },
				throwable: false,
				pinned: true,
				backgroundColor: "#D8CEC0",
			},
			{
				id: "e-dispatch",
				type: "paragraph",
				rect: { x: mx, y: 1220, width: w, height: 180 },
				throwable: false,
				pinned: true,
				text: DISPATCH,
				fontSize: 16,
				fontWeight: 400,
				fontFamily: SERIF,
				lineHeight: 26,
				color: "#2D2925",
			},
			{
				id: "e-briefs",
				type: "card",
				rect: { x: mx + w - 228, y: 1256, width: 228, height: 138 },
				throwable: true,
				pinned: false,
				text: "Inside this issue",
				fontSize: 14,
				fontWeight: 700,
				fontFamily: SANS,
				color: "#1A1612",
				backgroundColor: "#FFFDF8",
				borderRadius: 12,
				padding: 16,
				border: "1px solid #D9D0C2",
				boxShadow: "0 8px 24px rgba(26,22,18,0.05)",
				mass: 1.02,
				children: [
					{
						id: "briefs-a",
						type: "paragraph",
						rect: { x: 0, y: 10, width: 0, height: 0 },
						throwable: false,
						pinned: true,
						text: "Field report: dashboards that feel publishable",
						fontSize: 12,
						fontWeight: 500,
						fontFamily: SANS,
						lineHeight: 17,
						color: "#1A1612",
					},
					{
						id: "briefs-b",
						type: "paragraph",
						rect: { x: 0, y: 8, width: 0, height: 0 },
						throwable: false,
						pinned: true,
						text: "Essay: why layout engines need narrative ambition",
						fontSize: 12,
						fontWeight: 500,
						fontFamily: SANS,
						lineHeight: 17,
						color: "#1A1612",
					},
					{
						id: "briefs-c",
						type: "paragraph",
						rect: { x: 0, y: 8, width: 0, height: 0 },
						throwable: false,
						pinned: true,
						text: "Notebook: movable marginalia and reader agency",
						fontSize: 12,
						fontWeight: 500,
						fontFamily: SANS,
						lineHeight: 17,
						color: "#1A1612",
					},
				],
			},

			{
				id: "e-r8",
				type: "divider",
				rect: { x: mx, y: 1540, width: w, height: 1 },
				throwable: false,
				pinned: true,
				backgroundColor: "#CDBFAF",
			},
			{
				id: "e-foot",
				type: "heading",
				rect: { x: mx, y: 1554, width: w, height: 14 },
				throwable: false,
				pinned: true,
				text: "Printed in code  |  Powered by Pretext and Matter.js  |  Sunday editorial prototype",
				fontSize: 9,
				fontWeight: 500,
				fontFamily: MONO,
				lineHeight: 14,
				color: "#A19486",
			},
		],
	}
}
